import React, { useEffect, useState } from "react";
import { useForm, FormProvider, useFieldArray } from "react-hook-form";
import { apiMethods } from "@/api/index";
import { FormField } from "@/components/Form/FormField";
import { Button } from "@/components";
import type { AdminCategory } from "@/api/admin/categories/types";
import { Trash } from "lucide-react";

export type ProductFormValues = {
  name: string;
  slug?: string;
  description: string;
  gst_rate?: number;
  status?: "ACTIVE" | "INACTIVE";
  category: string;
  images: string[];
  stock?: number;
  isNew?: boolean;
  isCustomerFavourites?: boolean;
  isBestseller?: boolean;
  variants?: Array<{
    price: number;
    discountedPrice?: number;
    discountedPercent?: number;
    weight?: number;
    weightUnit?: "G" | "KG";
    status?: "ACTIVE" | "INACTIVE";
  }>;
};

interface ProductFormProps {
  title?: string;
  submitLabel?: string;
  isSubmitting?: boolean;
  defaultValues?: Partial<ProductFormValues>;
  categories?: AdminCategory[];
  onCancel: () => void;
  onSubmit: (values: ProductFormValues, action: "continue" | "return") => void;
  onDirtyChange?: (dirty: boolean) => void;
}

export function ProductForm({
  title = "Product Details",
  submitLabel = "Save Product",
  isSubmitting = false,
  defaultValues = {},
  categories = [],
  onCancel,
  onSubmit,
  onDirtyChange,
}: ProductFormProps) {
  console.log("ProductForm rendered with defaultValues:", defaultValues);
  const formMethods = useForm<ProductFormValues>({
    defaultValues: {
      name: "",
      slug: "",
      description: "",
      gst_rate: 18,
      status: "ACTIVE",
      category: "",
      images: [],
      stock: 0,
      isNew: false,
      isCustomerFavourites: false,
      isBestseller: false,
      variants: [],
      ...defaultValues,
    },
  });

  const { handleSubmit, reset, setValue, watch, control, formState } =
    formMethods;

  const {
    fields: variantFields,
    append: appendVariant,
    remove: removeVariant,
  } = useFieldArray({
    control,
    name: "variants",
  });

  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [submitAction, setSubmitAction] = useState<"continue" | "return">(
    "continue",
  );

  useEffect(() => {
    onDirtyChange?.(formState.isDirty ?? false);
  }, [formState.isDirty, onDirtyChange]);

  useEffect(() => {
    if (formState.isDirty) return;

    // Explicitly map the boolean flags to ensure they aren't undefined
    const merged: ProductFormValues = {
      name: defaultValues.name ?? "",
      slug: defaultValues.slug ?? "",
      description: defaultValues.description ?? "",
      gst_rate: defaultValues.gst_rate ?? 18,
      status: defaultValues.status ?? "ACTIVE",
      category: defaultValues.category ?? "",
      images: defaultValues.images ?? [],
      stock: defaultValues.stock ?? 0,
      // Ensure these are explicitly boolean
      isNew: !!defaultValues.isNew,
      isCustomerFavourites: !!defaultValues.isCustomerFavourites,
      isBestseller: !!defaultValues.isBestseller,
      variants: defaultValues.variants ?? [],
    };

    reset(merged);
  }, [defaultValues, reset, formState.isDirty]);

  const currentImages = watch("images");

  const handleUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (!files || files.length === 0) return;

    setUploading(true);
    setUploadError(null);

    try {
      const existingImages = watch("images") || [];
      const uploadedKeys: string[] = [];

      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const formData = new FormData();
        formData.append("file", file);
        formData.append("folder", "products");

        const response = await apiMethods.upload<{ url: string; key: string }>(
          "/uploads",
          formData,
        );
        const key = response.data?.key || response.data?.url;
        if (key) {
          uploadedKeys.push(key);
        }
      }

      setValue("images", [...existingImages, ...uploadedKeys], {
        shouldValidate: true,
      });
    } catch (error) {
      setUploadError("Image upload failed, please try again.");
      console.error("ProductForm upload error", error);
    } finally {
      setUploading(false);
      if (event.target) event.target.value = "";
    }
  };

  return (
    <div className="space-y-6 p-6 bg-slate-50 rounded-xl shadow-sm">
      {title && (
        <div className="flex justify-between items-center border-b border-slate-200 pb-3">
          <div>
            <h2 className="text-2xl font-bold text-slate-900">{title}</h2>
            <p className="text-sm text-slate-500 mt-1">
              Enter the product details and configure variants. SKU values are
              auto-generated by backend for consistency.
            </p>
          </div>
        </div>
      )}

      <FormProvider {...formMethods}>
        <form
          onSubmit={handleSubmit((values) => {
            const normalizedVariants = Array.isArray(values.variants)
              ? values.variants
                  .filter((variant) => variant.price !== undefined)
                  .map((variant) => ({
                    price: Number(variant.price),
                    discountedPrice:
                      variant.discountedPrice !== undefined
                        ? Number(variant.discountedPrice)
                        : undefined,
                    discountedPercent:
                      variant.discountedPercent !== undefined
                        ? Number(variant.discountedPercent)
                        : undefined,
                    weight:
                      variant.weight !== undefined
                        ? Number(variant.weight)
                        : undefined,
                    weightUnit: variant.weightUnit || "G",
                    status: variant.status || "ACTIVE",
                  }))
              : [];

            const normalized: ProductFormValues = {
              ...values,
              gst_rate: values.gst_rate ?? 18,
              images: values.images || [],
              variants: normalizedVariants,
            };
            onSubmit(normalized, submitAction);
          })}
          className="grid grid-cols-2 gap-4"
        >
          <FormField
            name="name"
            label="Product Name"
            required
            className="col-span-2"
          />
          <FormField
            name="slug"
            label="Slug"
            className="col-span-2"
            helperText="Helpful for clean URLs"
          />
          <FormField
            name="description"
            label="Description"
            type="textarea"
            className="col-span-2"
            required
          />
          <FormField
            name="gst_rate"
            label="GST Rate %"
            type="select"
            required
            options={[
              { value: "0", label: "0%" },
              { value: "5", label: "5%" },
              { value: "12", label: "12%" },
              { value: "18", label: "18%" },
              { value: "28", label: "28%" },
            ]}
          />
          <FormField
            name="status"
            label="Status"
            type="select"
            required
            options={[
              { value: "ACTIVE", label: "Active" },
              { value: "INACTIVE", label: "Inactive" },
            ]}
          />
          <FormField
            name="category"
            label="Category"
            type="select"
            required
            options={categories.map((cat) => ({
              value: cat.id,
              label: cat.name,
            }))}
          />
          <FormField name="stock" label="Stock (kg)" type="number" />

          <div className="col-span-2 space-y-4 mt-4">
            <h3 className="text-sm font-semibold text-slate-800 border-b border-slate-200 pb-2">
              Product Flags
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-6">
              <div className="max-w-xs">
                <FormField
                  name="isNew"
                  label="Mark as New Arrival"
                  type="checkbox"
                  helperText="Display this product in the 'New Arrivals' section"
                />
              </div>

              <div className="max-w-xs">
                <FormField
                  name="isCustomerFavourites"
                  label="Mark as Customer Favourite"
                  type="checkbox"
                  helperText="Highlight this product as a customer favorite"
                />
              </div>

              <div className="max-w-xs">
                <FormField
                  name="isBestseller"
                  label="Mark as Bestseller"
                  type="checkbox"
                  helperText="Display this product in the 'Bestsellers' section"
                />
              </div>
            </div>
          </div>

          <div className="col-span-2 rounded-md border border-slate-200 p-4 bg-white">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-sm font-semibold text-slate-800">
                Product Variants/Options
              </h3>
              <Button
                type="button"
                variant="secondary"
                onClick={() =>
                  appendVariant({
                    price: 0,
                    discountedPrice: undefined,
                    discountedPercent: undefined,
                    weight: 0,
                    weightUnit: "G",
                    status: "ACTIVE",
                  })
                }
              >
                Add Variant
              </Button>
            </div>

            {variantFields.length === 0 && (
              <p className="text-xs text-slate-500">No variants added yet.</p>
            )}

            <div className="grid grid-cols-12 gap-2">
              {variantFields.map((variant, index) => (
                <div
                  className="col-span-12 grid grid-cols-12 gap-2 border rounded-lg p-3 bg-slate-50 items-start"
                  key={variant.id}
                >
                  <FormField
                    name={`variants.${index}.weightUnit`}
                    label="Unit"
                    type="select"
                    options={[
                      { value: "G", label: "Grams (G)" },
                      { value: "KG", label: "Kilograms (KG)" },
                    ]}
                    className="col-span-4"
                  />
                  <FormField
                    name={`variants.${index}.weight`}
                    label="Weight"
                    type="number"
                    className="col-span-4"
                  />
                  <FormField
                    name={`variants.${index}.price`}
                    label="Price"
                    type="number"
                    required
                    className="col-span-4"
                  />
                  <FormField
                    name={`variants.${index}.discountedPrice`}
                    label="Discounted Price"
                    type="number"
                    className="col-span-4"
                  />
                  <FormField
                    name={`variants.${index}.discountedPercent`}
                    label="Discount %"
                    type="number"
                    className="col-span-4"
                  />
                  <FormField
                    name={`variants.${index}.status`}
                    label="Status"
                    type="select"
                    options={[
                      { value: "ACTIVE", label: "Active" },
                      { value: "INACTIVE", label: "Inactive" },
                    ]}
                    className="col-span-3"
                  />

                  {/* FIXED BUTTON CONTAINER */}
                  <div className="col-span-1 flex flex-col justify-end pb-1.5 h-full">
                    <Button
                      type="button"
                      variant="danger"
                      className="w-8 h-8 p-0 flex items-center justify-center min-w-0"
                      onClick={() => removeVariant(index)}
                    >
                      <Trash size={16} />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="col-span-2 space-y-2">
            <label className="block text-sm font-medium text-slate-700">
              Product Images
            </label>
            <input
              type="file"
              multiple
              accept="image/*"
              onChange={handleUpload}
              disabled={uploading}
              className="block w-full text-slate-600 text-sm file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
            />
            {uploading && (
              <p className="text-xs text-blue-600">Uploading images...</p>
            )}
            {uploadError && (
              <p className="text-xs text-red-500">{uploadError}</p>
            )}
            <div className="grid grid-cols-3 gap-2 mt-2">
              {currentImages && currentImages.length > 0 ? (
                currentImages.map((url, index) => (
                  <div
                    key={index}
                    className="aspect-square rounded-md overflow-hidden border border-slate-200 bg-slate-50 relative"
                  >
                    <img
                      src={url}
                      alt={`Preview ${index + 1}`}
                      className="w-full h-full object-cover"
                      onError={(e) => {
                        const target = e.currentTarget;
                        // Only swap if we aren't already showing the placeholder
                        // This stops the infinite loop even if placeholder.png is missing
                        if (!target.src.includes("placeholder.png")) {
                          target.src = "/placeholder.png";
                        }
                      }}
                    />
                    {/* Optional: Add a remove button here since we're fixing the UI */}
                    <button
                      type="button"
                      onClick={() => {
                        const newImages = currentImages.filter(
                          (_, i) => i !== index,
                        );
                        setValue("images", newImages, { shouldDirty: true });
                      }}
                      className="absolute top-1 right-1 bg-red-500 text-white rounded-full p-1 shadow-md hover:bg-red-600 transition-colors"
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        className="h-3 w-3"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={3}
                          d="M6 18L18 6M6 6l12 12"
                        />
                      </svg>
                    </button>
                  </div>
                ))
              ) : (
                <div className="col-span-3 py-8 border-2 border-dashed border-slate-200 rounded-md flex flex-col items-center justify-center">
                  <p className="text-sm text-slate-400 font-medium">
                    No images uploaded yet
                  </p>
                </div>
              )}
            </div>
          </div>

          <div className="col-span-2 flex justify-between gap-3 pt-4 border-t border-slate-200">
            <Button
              type="button"
              variant="outline"
              onClick={onCancel}
              disabled={isSubmitting}
            >
              Cancel
            </Button>

            <div className="flex gap-2">
              <Button
                type="button"
                variant="secondary"
                onClick={() => {
                  setSubmitAction("continue");
                  handleSubmit((values) => onSubmit(values, "continue"))();
                }}
                disabled={isSubmitting}
              >
                Save & Continue
              </Button>

              <Button
                type="button"
                variant="primary"
                onClick={() => {
                  setSubmitAction("return");
                  handleSubmit((values) => onSubmit(values, "return"))();
                }}
                disabled={isSubmitting}
              >
                Save & Return
              </Button>
            </div>
          </div>
        </form>
      </FormProvider>
    </div>
  );
}
