import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Outlet, Link, useLocation } from 'react-router-dom';
import { useState } from 'react';
import { Gauge, UserCircle, Buildings, ShoppingBagOpen, Package, ChartBar, Gear, SignOut, ListMagnifyingGlass, Bell, CaretLeft, CaretRight, } from '@phosphor-icons/react';
function Layout() {
    const [sidebarOpen, setSidebarOpen] = useState(true);
    const location = useLocation();
    const navItems = [
        { label: 'Dashboard', path: '/', icon: _jsx(Gauge, { size: 20, weight: "duotone" }) },
        { label: 'Users', path: '/users', icon: _jsx(UserCircle, { size: 20, weight: "duotone" }) },
        { label: 'Sellers', path: '/sellers', icon: _jsx(Buildings, { size: 20, weight: "duotone" }) },
        { label: 'Orders', path: '/orders', icon: _jsx(ShoppingBagOpen, { size: 20, weight: "duotone" }) },
        { label: 'Products', path: '/products', icon: _jsx(Package, { size: 20, weight: "duotone" }) },
        { label: 'Reports', path: '/reports', icon: _jsx(ChartBar, { size: 20, weight: "duotone" }) },
        { label: 'Settings', path: '/settings', icon: _jsx(Gear, { size: 20, weight: "duotone" }) },
    ];
    const isActive = (path) => location.pathname === path;
    return (_jsxs("div", { className: "flex h-screen bg-slate-50", children: [_jsxs("aside", { className: `${sidebarOpen ? 'w-72' : 'w-20'} bg-white border-r border-slate-200 shadow-lg transition-all duration-300 flex flex-col`, children: [_jsxs("div", { className: "p-4 border-b border-slate-200 flex items-center justify-between", children: [sidebarOpen ? (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600 text-white flex items-center justify-center font-black text-lg", children: "A" }), _jsxs("div", { children: [_jsx("h1", { className: "text-xl font-extrabold text-slate-900", children: "Sappey Admin" }), _jsx("p", { className: "text-xs text-slate-500", children: "Management Portal" })] })] })) : (_jsx("div", { className: "w-10 h-10 rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600 text-white flex items-center justify-center font-black text-lg", children: "A" })), _jsx("button", { className: "w-9 h-9 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-600 flex items-center justify-center", onClick: () => setSidebarOpen((open) => !open), children: sidebarOpen ? _jsx(CaretLeft, { size: 20, weight: "bold" }) : _jsx(CaretRight, { size: 20, weight: "bold" }) })] }), _jsx("nav", { className: "flex-1 px-2 py-4 space-y-2", children: navItems.map((item) => (_jsxs(Link, { to: item.path, className: `flex items-center gap-3 px-3 py-2 rounded-xl transition-all duration-200 ${isActive(item.path)
                                ? 'bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-lg'
                                : 'text-slate-700 hover:bg-slate-100 hover:text-slate-900'}`, children: [_jsx("div", { className: `${isActive(item.path) ? 'text-white' : 'text-slate-500'}`, children: item.icon }), sidebarOpen && _jsx("span", { className: "text-sm font-medium", children: item.label })] }, item.path))) }), _jsx("div", { className: "p-4 border-t border-slate-200", children: _jsxs("button", { className: "flex items-center gap-3 w-full p-3 rounded-xl text-slate-700 hover:bg-red-50 hover:text-red-600 transition-all duration-200", children: [_jsx(SignOut, { size: 20, weight: "duotone" }), sidebarOpen && _jsx("span", { className: "font-medium", children: "Logout" })] }) })] }), _jsxs("main", { className: "flex-1 overflow-auto", children: [_jsxs("div", { className: "h-16 sticky top-0 bg-white border-b border-slate-200 z-20 flex items-center justify-between px-6 shadow-sm", children: [_jsx("div", { className: "flex items-center gap-4", children: _jsxs("div", { className: "flex items-center gap-2 bg-slate-100 rounded-xl px-3 py-2", children: [_jsx(ListMagnifyingGlass, { size: 18, className: "text-slate-500" }), _jsx("input", { type: "text", placeholder: "Search...\r\n", className: "bg-transparent outline-none text-sm text-slate-700 placeholder:text-slate-400" })] }) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("button", { className: "relative p-2 rounded-lg text-slate-600 hover:bg-slate-100", children: [_jsx(Bell, { size: 20 }), _jsx("span", { className: "absolute right-1 top-1 h-2 w-2 rounded-full bg-red-500" })] }), _jsxs("div", { className: "flex items-center gap-2 p-2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-xl shadow-md", children: [_jsx("span", { className: "w-8 h-8 rounded-full bg-white text-blue-700 flex items-center justify-center font-bold", children: "A" }), sidebarOpen && _jsx("span", { className: "text-sm font-semibold", children: "Admin" })] })] })] }), _jsx("div", { className: "p-6 md:p-8", children: _jsx(Outlet, {}) })] })] }));
}
export default Layout;
